version:  '3.1'

services:
    api:
      image: abrahamg20/neopetcare:0.1
      restart: always
      ports: 
          - 8912:8080
      environment:
        DATABASE_HOST: db
        DATABASE_PORT: 3306
        DATABASE_NAME: bdneopetcare
        DATABASE_USERNAME: root
        DATABASE_PASSWORD: root
        
    db: 
        image: mysql:latest
        restart: always
        ports:
           - 7789:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bdneopetcare
            MYSQL_USER: root
            MYSQL_PASSWORD: root