version:  '3.1'

services:
  maven:
    image: maven:3.6.3-jdk-8-slim
    command: sh /tmp/testing.sh
    volumes:
      - ./src:/tmp/src
      - ./pom.xml:/tmp/pom.xml
      - ./testing.sh:/tmp/testing.sh
      - ./target:/tmp/target
      - mvn2_conf:/root/.m2

volumes:
  mvn2_conf: